USE DB_LOJA_MANHA;

-- 1°
SELECT DEP_NOME, DEP_DESCONTO FROM TB_DEPARTAMENTOS;

-- 2°
SELECT PRO_DES_PRODUTO, PRO_PRECO, PRO_QT_ESTOQUE FROM TB_PRODUTOS;

-- 3°
SELECT PRO_DES_PRODUTO, PRO_PRECO, PRO_QT_ESTOQUE, PRO_QT_MINIMA FROM TB_PRODUTOS
WHERE PRO_QT_ESTOQUE < 20;

-- 4°
SELECT PRO_DES_PRODUTO, PRO_PRECO, PRO_QT_ESTOQUE, PRO_QT_MINIMA FROM TB_PRODUTOS
WHERE PRO_QT_ESTOQUE > 20;

-- 5°
SELECT VEN_CODIGO, VEN_NOME, VEN_DT_ADMISSAO FROM TB_VENDEDORES
WHERE VEN_SEX_CODIGO = 2;

-- 6°
SELECT VEN_CODIGO, VEN_NOME, VEN_DT_ADMISSAO FROM TB_VENDEDORES
WHERE (VEN_SEX_CODIGO = 1 AND VEN_DT_ADMISSAO BETWEEN '2005-01-01' AND '2008-12-31');

-- 7°
SELECT CLI_NOME FROM TB_CLIENTES
WHERE CLI_NOME LIKE ('%SANTOS%');

-- 8°
SELECT PRO_DES_PRODUTO, PRO_PRECO FROM TB_PRODUTOS
ORDER BY PRO_PRECO ASC
LIMIT 2;

-- 9°
SELECT PRO_DES_PRODUTO, PRO_PRECO FROM TB_PRODUTOS
ORDER BY PRO_PRECO DESC
LIMIT 2;

-- 10°
SELECT VEN_CODIGO, VEN_DT_ADMISSAO FROM TB_VENDEDORES
ORDER BY VEN_DT_ADMISSAO ASC
LIMIT 3;