USE DB_LOJA_MANHA;

SELECT 
    FUN_MATRICULA AS 'MATRICULA',
    FUN_NOME AS 'FUNCIONARIO',
    AVG(VEN_TOTAL_VENDA) AS 'MEDIA VENDAS',
    COUNT(VEN_TOTAL_VENDA) AS 'QUANTIDADE VENDAS'
FROM
    TB_FUNCIONARIOS
        LEFT JOIN
    TB_VENDAS ON FUN_MATRICULA = VEN_FUN_MATRICULA
WHERE
    FUN_SEX_ID = 2
GROUP BY FUN_MATRICULA
HAVING AVG(VEN_TOTAL_VENDA) > 200.0
ORDER BY FUN_MATRICULA ASC;



SUM -> SOMAR
AVG -> MEDIA
COUNT -> CONTAR
MAX -> MAXIMO
MIN -> MINIMO