USE DB_LOCADORA;

SELECT 
    *
FROM
    TB_CATEGORIAS;

SELECT 
    CAT_ID, CAT_NOME
FROM
    TB_CATEGORIAS;

SELECT 
    CAT_NOME
FROM
    TB_CATEGORIAS
WHERE
    CAT_PRECO < 3;

SELECT 
    FIL_ID AS ID, FIL_TITULO AS FILME
FROM
    TB_FILMES
WHERE
    FIL_CLA_ID = 1;
    
SELECT 
    CLI_ID AS CÓDIGO, CLI_CPF AS CPF, CLI_NOME AS CLIENTE
FROM
    TB_CLIENTES
WHERE
    CLI_DT_NASCIMENTO BETWEEN '1991-01-01' AND '2000-12-31'
ORDER BY CLI_NOME ASC;

SELECT 
    CLI_ID AS CÓDIGO, CLI_CPF AS CPF, CLI_NOME AS CLIENTE
FROM
    TB_CLIENTES
ORDER BY CLI_DT_NASCIMENTO ASC
LIMIT 2;
