CREATE DATABASE IF NOT EXISTS DB_LOCADORA;
-- DROP DATABASE IF EXISTS DB_LOCADORA;

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_SEXOS(
	SEX_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    SEX_NOME VARCHAR(15) NOT NULL, 
    SEX_SIGLA CHAR(1) NOT NULL, 
    CONSTRAINT PRIMARY KEY(SEX_ID)
);

INSERT INTO TB_SEXOS 
	(SEX_NOME, SEX_SIGLA) 
VALUES 
	('MASCULINO', 'M'), 
    ('FEMININO', 'F');
    
CREATE TABLE IF NOT EXISTS TB_CATEGORIAS(
	CAT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    CAT_NOME VARCHAR(25) NOT NULL, 
    CAT_PRECO DECIMAL(4,2) NOT NULL, 
    CONSTRAINT PRIMARY KEY(CAT_ID)
);

INSERT INTO TB_CATEGORIAS 
	(CAT_NOME, CAT_PRECO) 
VALUES 
	('CATALOGO', 1.50), 
    ('LANÇAMENTO', 3.00), 
    ('SUPER-LANÇAMENTO', 5.00);
    
CREATE TABLE IF NOT EXISTS TB_GENEROS(
	GEN_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    GEN_NOME VARCHAR(20) NOT NULL, 
    CONSTRAINT PRIMARY KEY(GEN_ID)
);

INSERT INTO TB_GENEROS 
	(GEN_NOME) 
VALUES 
	('AÇÃO'),
    ('ANIMAÇÃO'),
    ('AVENTURA'),
    ('COMÉDIA'),
    ('DRAMA'),
    ('ROMANCE'),
    ('TERROR'),
    ('FANTASIA'),
    ('BIOGRAFIA'),
    ('ÉPICO'),
    ('ESPIONAGEM'),
    ('FICÇÃO CIENTIFICA'),
    ('FAMILIA');
    
CREATE TABLE IF NOT EXISTS TB_CLASSIFICACOES(
	CLA_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLA_NOME VARCHAR(20) NOT NULL,
    CLA_SIGLA VARCHAR(2) NOT NULL,
    CONSTRAINT PRIMARY KEY(CLA_ID)
);

INSERT INTO TB_CLASSIFICACOES 
	(CLA_NOME, CLA_SIGLA) 
VALUES 
	('LIVRE', 'L'),
    ('10 ANOS', '10'),
    ('12 ANOS', '12'),
    ('14 ANOS', '14');
    
CREATE TABLE IF NOT EXISTS TB_ATORES(
	ATO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ATO_NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY(ATO_ID)
);

INSERT INTO TB_ATORES
	(ATO_NOME)
VALUES
	('ELIJAH WOOD'),
    ('SEAN ASTIN'),
    ('LAN MCKELLEN'),
    ('RICHARD GERE'),
    ('JOAN ALLEN'),
    ('TOM CRUISE'),
    ('HENRY CAVILL'),
    ('REBECCA FERGUSON'),
    ('PAUL RUDD'),
    ('EVANGELINE LILLY'),
    ('MICHAEL PEÑA'),
    ('CRAIG T. NELSON'),
    ('HOLLY HUNTER'),
    ('HUCK MILNER'),
    ('ROBERT DE NIRO'),
    ('CUBA GOODING JR.'),
    ('ANDREW GARFIELD'),
    ('VINCE VAUGHN'),
    ('RUSSELL CROWE'),
    ('JOAQUIN PHOENIX'),
    ('DANIEL RADCLIFFE'),
    ('RUPERT GRINT'),
    ('ALBERT BROOKS'),
    ('ELLEN DEGENERES'),
    ('ALEXANDER GOULD');
    
CREATE TABLE IF NOT EXISTS TB_DIRETORES(
	DIR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DIR_NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY(DIR_ID)
);

INSERT INTO TB_DIRETORES
	(DIR_NOME)
VALUES
	('PETER JACKSON'),
    ('LASSE HALLSTROM'),
    ('CHRISTOPHER MCQUARRIE'),
    ('PEYTON REED'),
    ('BRAD BIRD'),
    ('GEORGE TILLMAN JR.'),
    ('MEL GIBSON'),
    ('RIDLEY SCOTT'),
    ('ALFONSO CUARÓN'),
    ('ANDREW STANTON'),
    ('LEE UNKRICH');
    
CREATE TABLE IF NOT EXISTS TB_FILMES(
	FIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIL_TITULO VARCHAR(80) NOT NULL,
    FIL_SINOPSE TEXT,
    FIL_ANO_LANCAMENTO SMALLINT UNSIGNED,
    FIL_DURACAO SMALLINT UNSIGNED,
    FIL_CLA_ID TINYINT UNSIGNED NOT NULL,
    FIL_CAT_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FIL_ID),
    CONSTRAINT FK_CLA_FIL FOREIGN KEY(FIL_CLA_ID) REFERENCES TB_CLASSIFICACOES(CLA_ID),
    CONSTRAINT FK_CAT_FIL FOREIGN KEY(FIL_CAT_ID) REFERENCES TB_CATEGORIAS(CAT_ID)
);

INSERT INTO TB_FILMES
	(FIL_TITULO, FIL_ANO_LANCAMENTO, FIL_DURACAO, FIL_CLA_ID, FIL_CAT_ID)
VALUES
	('SENHOR DOS ANÉIS - SOCIEDADE DO ANEL', 2002, 300, 3, 1),
    ('SEMPRE AO SEU LADO', 2009, 300, 2, 1),
    ('MISSÃO IMPOSSÍVEL - EFEITO FALLOUT', 2018, 300, 4, 3),
    ('HOMEM-FORMIGA E A VESPA', 2018, 300, 3, 3),
    ('OS INCRÍVEIS 2', 2018, 300, 1, 3),
    ('HOMENS DE HONRA', 2001, 300, 4, 1),
    ('ATÉ O ÚLTIMO HOMEM', 2017, 300, 4, 2),
    ('GLADIADOR', 2000, 300, 4, 1),
    ('HARRY POTTER E O PRISIONEIRO DE AZKABAN', 2004, 300, 4, 1),
    ('PROCURANDO NEMO', 2012, 300, 1, 1);
    
CREATE TABLE IF NOT EXISTS TB_GENEROS_FILMES(
	GDF_FIL_ID INT UNSIGNED NOT NULL,
    GDF_GEN_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(GDF_FIL_ID, GDF_GEN_ID),
    CONSTRAINT FK_FIL_GDF FOREIGN KEY(GDF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_GEN_GDF FOREIGN KEY(GDF_GEN_ID) REFERENCES TB_GENEROS(GEN_ID)
);

INSERT INTO TB_GENEROS_FILMES
	(GDF_FIL_ID, GDF_GEN_ID)
VALUES
	(1, 8), (1, 3),
    (2, 5),
    (3, 1), (3, 11),
    (4, 1), (4, 12), (4, 3),
    (5, 2), (5, 13),
    (6, 5), (6, 9),
    (7, 5), (7, 9),
    (8, 10), (8, 3),
    (9, 8), (9, 3),
    (10, 2), (10, 3);
    
CREATE TABLE IF NOT EXISTS TB_PAISES(
	PAI_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PAI_NOME VARCHAR(30) NOT NULL,
    PAI_SIGLA CHAR(3) NOT NULL,
    CONSTRAINT PRIMARY KEY(PAI_ID)
);

INSERT INTO TB_PAISES
	(PAI_SIGLA, PAI_NOME)
VALUES
	('BRA', 'BRASIL'),
    ('EUA', 'ESTADOS UNIDOS'),
    ('FRA', 'FRANÇA'),
    ('ITA', 'ITÁLIA');
    
ALTER TABLE TB_FILMES
ADD COLUMN FIL_PAI_ID TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE TB_FILMES
ADD CONSTRAINT FK_PAI_FIL FOREIGN KEY(FIL_PAI_ID) REFERENCES TB_PAISES(PAI_ID);

CREATE TABLE IF NOT EXISTS TB_DIRETORES_FILMES(
	DDF_FIL_ID INT UNSIGNED NOT NULL,
    DDF_DIR_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(DDF_FIL_ID, DDF_DIR_ID),
    CONSTRAINT FK_FIL_DDF FOREIGN KEY(DDF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_DIR_DDF FOREIGN KEY(DDF_DIR_ID) REFERENCES TB_DIRETORES(DIR_ID)
);

INSERT INTO TB_DIRETORES_FILMES
	(DDF_FIL_ID, DDF_DIR_ID)
VALUES
	(1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10), (10, 11);
    
CREATE TABLE TB_ATORES_FILMES(
	ADF_FIL_ID INT UNSIGNED NOT NULL,
    ADF_ATO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(ADF_FIL_ID, ADF_ATO_ID),
    CONSTRAINT FK_FIL_ADF FOREIGN KEY(ADF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_ATO_ADF FOREIGN KEY(ADF_ATO_ID) REFERENCES TB_ATORES(ATO_ID)
);
    
INSERT INTO TB_ATORES_FILMES
	(ADF_FIL_ID, ADF_ATO_ID)
VALUES
	(1, 1), (1, 2), (1, 3),
    (2, 4), (2, 5),
    (3, 6), (3, 7), (3, 8),
    (4, 9), (4, 10), (4, 11),
    (5, 12), (5, 13), (5, 14),
    (6, 15), (6, 16),
    (7, 17), (7, 18),
    (8, 19), (8, 20),
    (9, 21), (9, 22),
    (10, 23), (10, 24), (10, 25);
    
CREATE TABLE IF NOT EXISTS TB_STATUS(
	STT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    STT_STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(STT_ID)
);

INSERT INTO TB_STATUS
	(STT_STATUS)
VALUES
	('DISPONIVEL'),
    ('INDISPONIVEL');

CREATE TABLE IF NOT EXISTS TB_MIDIAS(
	MID_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MID_NOME VARCHAR(10) NOT NULL,
    CONSTRAINT PRIMARY KEY(MID_ID)
);

INSERT INTO TB_MIDIAS
	(MID_NOME)
VALUES
	('BLU-RAY');

CREATE TABLE IF NOT EXISTS TB_IDIOMAS(
	IDIO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDIO_NOME VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(IDIO_ID)
);

INSERT INTO TB_IDIOMAS
	(IDIO_NOME)
VALUES
	('INGLÊS'),
    ('PORTUGUÊS'),
    ('FRANCÊS'),
    ('ESPANHOL'),
    ('ITALIANO'),
    ('JAPONÊS'),
    ('RUSSO');

CREATE TABLE IF NOT EXISTS TB_COPIAS(
	COP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    COP_MID_ID TINYINT UNSIGNED NOT NULL,
    COP_STT_ID TINYINT UNSIGNED NOT NULL,
    COP_FIL_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(COP_ID),
    CONSTRAINT FK_MID_COP FOREIGN KEY(COP_MID_ID) REFERENCES TB_MIDIAS(MID_ID),
    CONSTRAINT FK_FIL_COP FOREIGN KEY(COP_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_STT_COP FOREIGN KEY(COP_STT_ID) REFERENCES TB_STATUS(STT_ID)
);

INSERT INTO TB_COPIAS
	(COP_FIL_ID, COP_MID_ID, COP_STT_ID)
VALUES
	(1, 1, 1);

CREATE TABLE IF NOT EXISTS TB_OBSERVACOES(
	ODC_COP_ID INT UNSIGNED NOT NULL,
    ODC_OBSERVACOES TEXT NOT NULL,
    CONSTRAINT PRIMARY KEY(ODC_COP_ID),
    CONSTRAINT FK_COP_ODC FOREIGN KEY(ODC_COP_ID) REFERENCES TB_COPIAS(COP_ID)
);

INSERT INTO TB_OBSERVACOES
	(ODC_COP_ID, ODC_OBSERVACOES)
VALUES
	(1, 'ISTO É UMA OBSERVAÇÃO!');

CREATE TABLE IF NOT EXISTS TB_AUDIO_COPIAS(
	ADC_COP_ID INT UNSIGNED NOT NULL,
    ADC_IDIO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(ADC_COP_ID, ADC_IDIO_ID),
    CONSTRAINT FK_IDIO_ADC FOREIGN KEY(ADC_IDIO_ID) REFERENCES TB_IDIOMAS(IDIO_ID),
    CONSTRAINT FK_COP_ADC FOREIGN KEY(ADC_COP_ID) REFERENCES TB_COPIAS(COP_ID)
);

INSERT INTO TB_AUDIO_COPIAS
	(ADC_COP_ID, ADC_IDIO_ID)
VALUES
	(1, 2);

CREATE TABLE IF NOT EXISTS TB_LEGENDAS_COPIAS(
	LDC_COP_ID INT UNSIGNED NOT NULL,
    LDC_IDIO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(LDC_COP_ID, LDC_IDIO_ID),
    CONSTRAINT FK_COP_ID FOREIGN KEY(LDC_COP_ID) REFERENCES TB_COPIAS(COP_ID),
    CONSTRAINT FK_IDIO_ID FOREIGN KEY(LDC_IDIO_ID) REFERENCES TB_IDIOMAS(IDIO_ID)
);

INSERT INTO TB_LEGENDAS_COPIAS
	(LDC_COP_ID, LDC_IDIO_ID)
VALUES
	(1, 2);



CREATE TABLE IF NOT EXISTS TB_CLIENTES(
	CLI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLI_CPF VARCHAR(11) NOT NULL,
    CLI_NOME VARCHAR(30) NOT NULL,
    CLI_RG VARCHAR(9) NOT NULL,
    CLI_DT_NASCIMENTO DATE NOT NULL,
    CLI_CEP VARCHAR(8) NOT NULL,
    CLI_LOGRADOURO VARCHAR(30) NOT NULL,
    CLI_COMPLEMENTO VARCHAR(30) NOT NULL,
    CLI_NUMERO_RESIDENCIA NUMERIC NOT NULL,
    CLI_SEX_ID TINYINT UNSIGNED NOT NULL,
    CLI_UF_ID INT UNSIGNED NOT NULL,
    CLI_CID_ID INT UNSIGNED NOT NULL,
    CLI_BAI_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(CLI_ID),
    CONSTRAINT UNIQUE KEY(CLI_CPF),
    CONSTRAINT FK_CLI_SEX FOREIGN KEY(CLI_SEX_ID) REFERENCES TB_SEXOS(SEX_ID),
    CONSTRAINT FK_CLI_UF FOREIGN KEY(CLI_UF_ID) REFERENCES TB_UFS(UF_ID),
    CONSTRAINT FK_CLI_CID FOREIGN KEY(CLI_CID_ID) REFERENCES TB_CIDADES(CID_ID),
    CONSTRAINT FK_CLI_BAI FOREIGN KEY(CLI_BAI_ID) REFERENCES TB_BAIRROS(BAI_ID)
);

INSERT INTO TB_CLIENTES
	(CLI_CPF, CLI_NOME, CLI_RG, CLI_DT_NASCIMENTO, CLI_CEP, CLI_LOGRADOURO, CLI_COMPLEMENTO, CLI_NUMERO_RESIDENCIA, CLI_SEX_ID, CLI_UF_ID, CLI_CID_ID, CLI_BAI_ID)
VALUES
	();



CREATE TABLE IF NOT EXISTS TB_UFS(
	UF_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    UF_NOME VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(UF_ID)
);

INSERT INTO TB_UFS
	(UF_ID, UF_NOME)
VALUES
	();

CREATE TABLE IF NOT EXISTS TB_CIDADES(
	CID_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CID_NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PRIMARY KEY(CID_ID)
);

INSERT INTO TB_CIDADES
	(CID_ID, CID_NOME)
VALUES
	();

CREATE TABLE IF NOT EXISTS TB_BAIRROS(
	BAI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    BAI_NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PRIMARY KEY(BAI_ID)
);

INSERT INTO TB_BAIRROS
	(BAI_ID, BAI_NOME)
VALUES
	();











