CREATE DATABASE IF NOT EXISTS DB_LOCADORA;
-- DROP DATABASE IF EXISTS DB_LOCADORA;

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_SEXOS(
	SEX_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    SEX_NOME VARCHAR(15) NOT NULL, 
    SEX_SIGLA CHAR(1) NOT NULL, 
    CONSTRAINT PRIMARY KEY(SEX_ID)
);

INSERT INTO TB_SEXOS 
	(SEX_NOME, SEX_SIGLA) 
VALUES 
	('MASCULINO', 'M'), 
    ('FEMININO', 'F');
    
CREATE TABLE IF NOT EXISTS TB_CATEGORIAS(
	CAT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    CAT_NOME VARCHAR(25) NOT NULL, 
    CAT_PRECO DECIMAL(2,2) NOT NULL, 
    CONSTRAINT PRIMARY KEY(CAT_ID)
);

INSERT INTO TB_CATEGORIAS 
	(CAT_NOME, CAT_PRECO) 
VALUES 
	('CATALOGO', 1.50), 
    ('LANÇAMENTO', 3.00), 
    ('SUPER-LANÇAMENTO', 5.00);
    
CREATE TABLE IF NOT EXISTS TB_GENEROS(
	GEN_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    GEN_NOME VARCHAR(20) NOT NULL, 
    CONSTRAINT PRIMARY KEY(GEN_ID)
);

INSERT INTO TB_GENEROS 
	(GEN_NOME) 
VALUES 
	('AÇÃO'),
    ('ANIMAÇÃO'),
    ('AVENTURA'),
    ('COMÉDIA'),
    ('DRAMA'),
    ('ROMANCE'),
    ('TERROR');
    
CREATE TABLE IF NOT EXISTS TB_CLASSIFICACOES(
	CLA_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLA_NOME VARCHAR(20) NOT NULL,
    CLA_SIGLA VARCHAR(2) NOT NULL,
    CONSTRAINT PRIMARY KEY(CLA_ID)
);

INSERT INTO TB_CLASSIFICACOES 
	(CLA_NOME, CLA_SIGLA) 
VALUES 
	('LIVRE', 'L'),
    ('10 ANOS', '10'),
    ('12 ANOS', '12'),
    ('14 ANOS', '14');
    
CREATE TABLE IF NOT EXISTS TB_ATORES(
	ATO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ATO_NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY(ATO_ID)
);

INSERT INTO TB_ATORES
	(ATO_NOME)
VALUES
	('NICOLAS CAGE'),
    ('BRAD PITT'),
    ('ADAM SANDLER'),
    ('JULIA ROBERTS'),
    ('ROBERT DE NIRO'),
    ('DENZEL WASHINGTON'),
    ('BRUCE WILLIS'),
    ('JOHN WAYNE');
    
CREATE TABLE IF NOT EXISTS TB_DIRETORES(
	DIR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DIR_NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY(DIR_ID)
);

INSERT INTO TB_DIRETORES
	(DIR_NOME)
VALUES
	('MICHAEL HENEKE'),
    ('PEDRO ALMODÓVAR'),
    ('MARTIN SCORSESE'),
    ('FEDERICO FELLINI'),
    ('ALFRED HITCHCOCK'),
    ('QUENTIN TARANTINO'),
    ('ROMAN POLANSKI'),
    ('WOODY ALLEN');
    
CREATE TABLE IF NOT EXISTS TB_FILMES(
	FIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIL_TITULO VARCHAR(80) NOT NULL,
    FIL_SINOPSE TEXT,
    FIL_ANO_LANCAMENTO SMALLINT UNSIGNED,
    FIL_DURACAO SMALLINT UNSIGNED,
    FIL_CLA_ID TINYINT UNSIGNED NOT NULL,
    FIL_CAT_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FIL_ID),
    CONSTRAINT FK_CLA_FIL FOREIGN KEY(FIL_CLA_ID) REFERENCES TB_CLASSIFICACOES(CLA_ID),
    CONSTRAINT FK_CAT_FIL FOREIGN KEY(FIL_CAT_ID) REFERENCES TB_CATEGORIAS(CAT_ID)
);

INSERT INTO TB_FILMES
	(FIL_TITULO, FIL_ANO_LANCAMENTO, FIL_DURACAO, FIL_CLA_ID, FIL_CAT_ID)
VALUES
	('SENHOR DOS ANÉIS - SOCIEDADE DO ANEL', 2002, 300, 3, 1),
    ('SEMPRE AO SEU LADO', 2009, 300, 2, 1),
    ('MISSÃO IMPOSSÍVEL - EFEITO FALLOUT', 2018, 300, 4, 3),
    ('HOMEM-FORMIGA E A VESPA', 2018, 300, 3, 3),
    ('OS INCRÍVEIS 2', 2018, 300, 1, 3),
    ('HOMENS DE HONRA', 2001, 300, 4, 1),
    ('ATÉ O ÚLTIMO HOMEM', 2017, 300, 4, 2),
    ('GLADIADOR', 2000, 300, 4, 1),
    ('HARRY POTTER E O PRISIONEIRO DE AZKABAN', 2004, 300, 4, 1),
    ('PROCURANDO NEMO', 2012, 300, 1, 1);
    
CREATE TABLE IF NOT EXISTS TB_GENEROS_FILMES(
	GDF_FIL_ID INT UNSIGNED NOT NULL,
    GDF_GEN_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(GDF_FIL_ID, GDF_GEN_ID),
    CONSTRAINT FK_FIL_GDF FOREIGN KEY(GDF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_GEN_GDF FOREIGN KEY(GDF_GEN_ID) REFERENCES TB_GENEROS(GEN_ID)
);

INSERT INTO TB_GENEROS_FILMES
	(GDF_FIL_ID, GDF_GEN_ID)
VALUES
	(1, 1), (1, 8),
    (2, 9),
    (3, 1),
    (4, 1), (4, 8), (4, 3),
    (5, 2), (5, 10),
    (6, 9), (6, 11),
    (7, 9), (7, 11),
    (8, 12), (8, 3),
    (9, 13), (9, 3),
    (10, 2), (10, 3);

USE DB_LOCADORA;
    
CREATE TABLE IF NOT EXISTS TB_PAISES(
	PAI_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PAI_NOME VARCHAR(30) NOT NULL,
    PAI_SIGLA CHAR(3) NOT NULL,
    CONSTRAINT PRIMARY KEY(PAI_ID)
);

INSERT INTO TB_PAISES
	(PAI_SIGLA, PAI_NOME)
VALUES
	('BRA', 'BRASIL'),
    ('EUA', 'ESTADOS UNIDOS'),
    ('FRA', 'FRANÇA'),
    ('ITA', 'ITÁLIA');
    
ALTER TABLE TB_FILMES
ADD COLUMN FIL_PAI_ID TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE TB_FILMES
ADD CONSTRAINT FK_PAI_FIL FOREIGN KEY(FIL_PAI_ID) REFERENCES TB_PAISES(PAI_ID);

CREATE TABLE IF NOT EXISTS TB_DIRETORES_FILMES(
	DDF_FIL_ID INT UNSIGNED NOT NULL,
    DDF_DIR_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(DDF_FIL_ID, DDF_DIR_ID),
    CONSTRAINT FK_FIL_DDF FOREIGN KEY(DDF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_DIR_DDF FOREIGN KEY(DDF_DIR_ID) REFERENCES TB_DIRETORES(DIR_ID)
);

INSERT INTO TB_DIRETORES_FILMES
	(DDF_FIL_ID, DDF_DIR_ID)
VALUES
	(1, 9),
    (2, 10),
    (3, 11),
    (4, 12),
    (5, 13),
    (6, 14),
    (7, 15),
    (8, 16),
    (9, 17),
    (10, 18), (10, 19);
    
CREATE TABLE TB_ATORES_FILMES(
	ADF_FIL_ID INT UNSIGNED NOT NULL,
    ADF_ATO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(ADF_FIL_ID, ADF_ATO_ID),
    CONSTRAINT FK_FIL_ADF FOREIGN KEY(ADF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_ATO_ADF FOREIGN KEY(ADF_ATO_ID) REFERENCES TB_ATORES(ATO_ID)
);
    
INSERT INTO TB_ATORES_FILMES
	(ADF_FIL_ID, ADF_ATO_ID)
VALUES
	(1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16),
    (2, 17), (2, 18), (2, 19),
    (3, 20), (3, 21), (3, 22),
    (4, 23), (4, 24), (4, 25),
    (5, 26), (5, 27), (5, 28),
    (6, 5), (6, 29),
    (7, 30), (7, 31),
    (8, 32), (8, 33),
    (9, 36), (9, 37),
    (10, 38), (10, 39);
    
CREATE TABLE IF NOT EXISTS TB_STATUS(
	STT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    STT_STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(STT_ID)
);

INSERT INTO TB_STATUS
	(STT_STATUS)
VALUES
	('DISPONIVEL'),
    ('INDISPONIVEL');

CREATE TABLE IF NOT EXISTS TB_MIDIAS(
	MID_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MID_NOME VARCHAR(10) NOT NULL,
    CONSTRAINT PRIMARY KEY(MID_ID)
);

INSERT INTO TB_MIDIAS
	(MID_NOME)
VALUES
	('BLU-RAY');

CREATE TABLE IF NOT EXISTS TB_IDIOMAS(
	IDIO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDIO_NOME VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(IDIO_ID)
);

INSERT INTO TB_IDIOMAS
	(IDIO_NOME)
VALUES
	('INGLÊS'),
    ('PORTUGUÊS'),
    ('FRANCÊS'),
    ('ESPANHOL'),
    ('ITALIANO'),
    ('JAPONÊS'),
    ('RUSSO');

CREATE TABLE IF NOT EXISTS TB_COPIAS(
	COP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    COP_MID_ID TINYINT UNSIGNED NOT NULL,
    COP_STT_ID TINYINT UNSIGNED NOT NULL,
    COP_FIL_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(COP_ID),
    CONSTRAINT FK_MID_COP FOREIGN KEY(COP_MID_ID) REFERENCES TB_MIDIAS(MID_ID),
    CONSTRAINT FK_FIL_COP FOREIGN KEY(COP_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_STT_COP FOREIGN KEY(COP_STT_ID) REFERENCES TB_STATUS(STT_ID)
);

INSERT INTO TB_COPIAS
	(COP_FIL_ID, COP_MID_ID, COP_STT_ID)
VALUES
	(1, 1, 1);

CREATE TABLE IF NOT EXISTS TB_OBSERVACOES(
	ODC_COP_ID INT UNSIGNED NOT NULL,
    ODC_OBSERVACOES TEXT NOT NULL,
    CONSTRAINT PRIMARY KEY(ODC_COP_ID),
    CONSTRAINT FK_COP_ODC FOREIGN KEY(ODC_COP_ID) REFERENCES TB_COPIAS(COP_ID)
);

INSERT INTO TB_OBSERVACOES
	(ODC_COP_ID, ODC_OBSERVACOES)
VALUES
	(1, 'ISTO É UMA OBSERVAÇÃO!');

CREATE TABLE IF NOT EXISTS TB_AUDIO_COPIAS(
	ADC_COP_ID INT UNSIGNED NOT NULL,
    ADC_IDIO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(ADC_COP_ID, ADC_IDIO_ID),
    CONSTRAINT FK_IDIO_ADC FOREIGN KEY(ADC_IDIO_ID) REFERENCES TB_IDIOMAS(IDIO_ID),
    CONSTRAINT FK_COP_ADC FOREIGN KEY(ADC_COP_ID) REFERENCES TB_COPIAS(COP_ID)
);

INSERT INTO TB_AUDIO_COPIAS
	(ADC_COP_ID, ADC_IDIO_ID)
VALUES
	(1, 2);

CREATE TABLE IF NOT EXISTS TB_LEGENDAS_COPIAS(
	LDC_COP_ID INT UNSIGNED NOT NULL,
    LDC_IDIO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(LDC_COP_ID, LDC_IDIO_ID),
    CONSTRAINT FK_COP_ID FOREIGN KEY(LDC_COP_ID) REFERENCES TB_COPIAS(COP_ID),
    CONSTRAINT FK_IDIO_ID FOREIGN KEY(LDC_IDIO_ID) REFERENCES TB_IDIOMAS(IDIO_ID)
);

INSERT INTO TB_LEGENDAS_COPIAS
	(LDC_COP_ID, LDC_IDIO_ID)
VALUES
	(1, 2);