

-- Clientes da decada de 90.
SELECT CLI_ID AS CÓDIGO, CLI_CPF AS CPF, CLI_NOME AS CLIENTE
FROM TB_CLIENTES
WHERE CLI_DT_NASCIMENTO BETWEEN '1991-01-01' AND '2000-12-31'
ORDER BY CLI_NOME ASC;

-- Cliente mais velho.
SELECT CLI_ID AS CÓDIGO, CLI_CPF AS CPF, CLI_NOME AS CLIENTE
FROM TB_CLIENTES
ORDER BY CLI_DT_NASCIMENTO ASC
LIMIT 1;