USE DB_LOJA_MANHA;
-- CREATE DATABASE IF NOT EXISTS DB_LOJA_MANHA;
-- DROP DATABASE DB_LOJA_MANHA;

INSERT INTO TB_DEPARTAMENTOS
	(DEP_DESCONTO, DEP_NOME)
VALUES
	(0.05, 'BOLAS'),
    (0.10, 'UNIFORME DE SELEÇÕES'),
    (0.08, 'ACESSORIOS'),
    (0.15, 'CALÇADOS'),
    (0.15, 'CHUTEIRAS'),
    (0.20, 'BICICLETAS');

INSERT INTO TB_MARCAS
	(MAR_MARCA)
VALUES
	('PENALTY'),
    ('TOPPER'),
    ('ADIDAS'),
    ('NIKE'),
    ('DP81'),
    ('OLYMPIKUS'),
    ('SHIMANO');

INSERT INTO TB_PRODUTOS
	(PRO_DEP_CODIGO, PRO_MAR_CODIGO, PRO_NOME, PRO_QT_ESTOQUE, PRO_QT_MINIMA, PRO_DES_PRODUTO, PRO_PRECO)
VALUES
	(1, 3, 'BOLA FUTSAL ADIDAS', 10, 15, 'Na versão para futebol de salão, a bola Futsal adidas... homenageia a bola oficial da copa!', 99.99),
    (2, 4, 'CAMISA NIKE BRASIL', 50, 10, 'Inspirada no mesmo tom do manto da vitoriosa Seleção Canarinho de 1970, a nova camisa da Seleção Brasileira...', 249.90),
    (6, 7, 'BICICLETA SOUTH LEGEND 2017', 20, 5, 'Bicicleta aro 29 Legend 2017 24 velocidades é a combinação perfeita com seus passeios e trilhas.', 899.00),
    (6, 7, 'BICICLETA ARO 29 MTB', 20, 5, 'Para conquistar excelente desempenho nas trilhas de mountain bike conte com a Bicicleta Aro 29 MTB Endorphine 4.3 - 2018', 1077.99),
    (4, 6, 'TÊNIS OLYMPIKUS FUTURE', 100, 20, 'Use o Tênis Olympikus Future Masculino para melhor performance das caminhadas.', 139.99);

INSERT INTO TB_ESTADOS
	(EST_ESTADO)
VALUES
	('RIO GRANDE DO NORTE');

INSERT INTO TB_CIDADES
	(CID_EST_CODIGO, CID_CIDADE)
VALUES
    (1, 'NATAL'),
    (1, 'PARNAMIRIM');

INSERT INTO TB_BAIRROS
	(BAI_CID_CODIGO, BAI_BAIRRO)
VALUES
	(1, 'TIROL'),
    (1, 'ALECRIM'),
    (1, 'RIBEIRA'),
    (2, 'CAJUPIRANGA'),
    (2, 'JARDIM PLANALTO'),
    (2, 'BOA ESPERANÇA');

INSERT INTO TB_CLIENTES
	(CLI_BAI_CODIGO, CLI_NOME, CLI_NUMERO, CLI_LOGRADOURO)
VALUES
	(2, 'PEDRO GUSTAVO', 'S/N', 'TRAVESSA MARCÍLIO DIAS'),
    (1, 'RAÍSSA JULIANA', '34-A', 'RUA AÇU'),
    (5, 'LEONORA ANNYS', '56', 'TRAVESSA CAJUPIRANGA'),
    (3, 'MARIA DA GLÓRIA', '85', 'AVENIDA ITAMARAJU');

CREATE TABLE IF NOT EXISTS TB_TEL_CLIENTES(
	TEC_CLI_CODIGO INTEGER UNSIGNED NOT NULL,
    TEC_TELEFONE VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY(TEC_CLI_CODIGO, TEC_TELEFONE),
    CONSTRAINT FK_CLI_TEC FOREIGN KEY(TEC_CLI_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO)
);

INSERT INTO TB_TEL_CLIENTES
	(TEC_CLI_CODIGO, TEC_TELEFONE)
VALUES
	(1, '996852584'),
    (2, '998254565'),
    (3, '988542585'),
    (4, '998124563');

INSERT INTO TB_FORNECEDORES
	(FOR_BAI_CODIGO, FOR_NOME, FOR_CNPJ, FOR_WEBSITE, FOR_DES_MUNICIPAL, FOR_DES_ESTADUAL, FOR_LOGRADOURO, FOR_NUMERO, FOR_CEP)
VALUES
	(2, 'JOSENILDO DUARTE', '15975385245612', 'WWW.BLABLA.COM.BR', 'BLABLABLA', 'BLABLABLA', 'TRAVESSA MARCÍLIO DIAS', '360', '59258456'),
    (4, 'JOSINALDO DUARTE', '12365478996312', 'WWW.BLABLA.COM.BR', 'BLABLABLA', 'BLABLABLA', 'AVENIDA MARANHÃO', '450', '59458752');

CREATE TABLE IF NOT EXISTS TB_TEL_FORNECEDORES(
	TEF_FOR_CODIGO INTEGER UNSIGNED NOT NULL,
    TEF_TELEFONE VARCHAR(12) NOT NULL,
    CONSTRAINT PRIMARY KEY(TEF_FOR_CODIGO, TEF_TELEFONE),
    CONSTRAINT FK_FOR_TEF FOREIGN KEY(TEF_FOR_CODIGO) REFERENCES TB_CLIENTES(CLI_CODIGO)
);

INSERT INTO TB_TEL_FORNECEDORES
	(TEF_FOR_CODIGO, TEF_TELEFONE)
VALUES
	(1, '988532548'),
    (2, '999187069');











