-- Lista.2
USE DB_LOJA_MANHA;

-- 1°
SELECT 
    DEP_NOME AS 'NOME DO DEPARTAMENTO',
    PRO_DES_PRODUTO AS 'DESCRIÇÃO DO PRODUTO',
    PRO_PRECO AS 'VALOR DO PRODUTO',
    DEP_DESCONTO AS 'DESCONTO'
FROM
    TB_DEPARTAMENTOS
        JOIN
    TB_PRODUTOS ON DEP_CODIGO = PRO_DEP_CODIGO
WHERE
    PRO_QT_ESTOQUE > PRO_QT_MINIMA
ORDER BY DEP_NOME ASC;

-- 2°
SELECT 
    DEP_NOME AS 'NOME DO DEPARTAMENTO',
    PRO_DES_PRODUTO AS 'DESCRIÇÃO DO PRODUTO',
    PRO_PRECO AS 'VALOR PRODUTO',
    DEP_DESCONTO AS 'DESCONTO'
FROM
    TB_DEPARTAMENTOS
        JOIN
    TB_PRODUTOS ON DEP_CODIGO = PRO_DEP_CODIGO
WHERE
    DEP_NOME = 'CALÇADOS';

-- 3°
SELECT 
    CLI_NOME, TEC_TELEFONE
FROM
    TB_CLIENTES
        JOIN
    TB_TEL_CLIENTES ON CLI_CODIGO = TEC_CLI_CODIGO
WHERE
    CLI_BAI_CODIGO IN ((SELECT 
            BAI_CODIGO
        FROM
            TB_BAIRROS
        WHERE
            BAI_BAIRRO = 'TIROL') , (SELECT 
                BAI_CODIGO
            FROM
                TB_BAIRROS
            WHERE
                BAI_BAIRRO = 'ALECRIM'),
        (SELECT 
                BAI_CODIGO
            FROM
                TB_BAIRROS
            WHERE
                BAI_BAIRRO = 'RIBEIRA'))
ORDER BY CLI_NOME ASC;

-- 4°
SELECT 
    FOR_NOME AS 'NOME', TEF_TELEFONE AS 'TELEFONE'
FROM
    TB_FORNECEDORES
        JOIN
    TB_FONES_FORNECEDORES ON FOR_ID = FDF_FOR_ID
        JOIN
    TB_CEPS ON CEP_ID = FOR_CEP_ID
        JOIN
    TB_BAIRROS ON BAI_ID = CEP_BAI_ID
        JOIN
    TB_CIDADES ON CID_ID = BAI_CID_ID
WHERE
    CID_NOME IN ('NATAL' , 'PARNAMIRIM')
ORDER BY FOR_NOME ASC;

-- 5°
SELECT 
    VEN_NOTA_FISCAL AS 'NOTA FISCAL',
    VEN_DATA_VENDA AS 'DATA',
    FDP_NOME AS 'PAGAMENTO',
    FUN_NOME AS 'FUNCIONARIO'
FROM
    TB_VENDAS
        JOIN
    TB_FOMAS_PAGAMENTOS ON VND_FDP_ID
        JOIN
    TB_FUNCIONARIOS ON FUN_MATRICULA = VEN_FUN_MATRICULA;

-- 6°
SELECT 
    VEN_NOTA_FISCAL AS 'NOTA FISCAL',
    VEN_DATA_VENDA AS 'DATA',
    FDP_NOME AS 'PAGAMENTO',
    FUN_NOME AS 'FUNCIONARIO'
FROM
    TB_VENDAS
        JOIN
    TB_FOMAS_PAGAMENTOS ON VND_FDP_ID
        JOIN
    TB_FUNCIONARIOS ON FUN_MATRICULA = VEN_FUN_MATRICULA
WHERE VEN_DATA_VENDA LIKE '2012-03-%';

-- 7°
SELECT DISTINCT
    PRO_NOME, DEP_NOME
FROM
    TB_COMPRAS
        JOIN
    TB_ITENS_COMPRAS ON COM_ID = IDC_COM_ID
        JOIN
    TB_PRODUTOS ON IDC_PRO_ID = PRO_ID
        JOIN
    TB_DEPARTAMENTOS ON PRO_DEP_ID = DEP_ID
WHERE
    COM_DATA_COMPRA BETWEEN '2012-03-01' AND '2012-03-31';

-- 8°
SELECT DISTINCT
    PRO_NOME, DEP_NOME
FROM
    TB_PRODUTOS
        JOIN
    TB_DEPARTAMENTOS ON DEP_ID = PRO_DEP_ID
        JOIN
    TB_ITENS_VENDA ON PRO_ID = IDV_PRO_ID
        JOIN
    TB_VENDAS ON VEN_ID = IDV_VEN_ID
WHERE
    DEP_NOME = 'UNIFORMES';

-- 9°
SELECT DISTINCT
    PRO_NOME, DEP_NOME
FROM
    TB_PRODUTOS
        JOIN
    TB_DEPARTAMENTOS ON DEP_ID = PRO_DEP_ID
        JOIN
    TB_ITENS_VENDA ON PRO_ID = IDV_PRO_ID
        JOIN
    TB_VENDAS ON VEN_ID = IDV_VEN_ID
        JOIN
    TB_FUNCIONARIOS ON FUN_MATRICULA = VEN_FUN_MATRICULA
WHERE
    FUN_MATRICULA = 2
        AND VEN_DATA_VENDA BETWEEN '2012-01-01' AND '2012-06-30'

-- 10°
SELECT 
    FUN_NOME
FROM
    TB_FUNCIONARIOS
        LEFT JOIN
    TB_VENDAS ON FUN_MATRICULA = VEN_FUN_MATRICULA
WHERE
    VEN_ID IS NULL;