-- Lista.3
USE DB_LOJA_MANHA;

-- 1°
SELECT 
    CID_NOME AS 'CIDADE', BAI_NOME AS 'BAIRRO'
FROM
    TB_CIDADES
        LEFT JOIN
    TB_BAIRROS ON CID_ID = BAI_CID_ID;

-- 2°
SELECT 
    CID_NOME AS 'CIDADE'
FROM
    TB_CIDADES
        LEFT JOIN
    TB_BAIRROS ON CID_ID = BAI_CID_ID
WHERE
    BAI_ID IS NULL;

-- 3°
SELECT 
    MAR_NOME AS 'MARCA'
FROM
    TB_MARCAS
        LEFT JOIN
    TB_PRODUTOS ON MAR_ID = PRO_MAR_ID
WHERE
    PRO_ID IS NULL;

-- 4°
SELECT 
    PRO_NOME AS 'NOME'
FROM
    TB_PRODUTOS
        LEFT JOIN
    TB_ITENS_VENDAS ON PRO_ID = IDV_PRO_ID
WHERE
    IDV_VEN_ID IS NULL;

-- 5°
SELECT 
    FUN_NOME AS 'NOME', FDF_FONE AS 'FONE'
FROM
    TB_FUNCIONARIOS
        LEFT JOIN
    TB_VENDAS ON FUN_MATRICULA = VEN_FUN_MATRICULA
        JOIN
    TB_FONES_FUNCIONARIOS ON FUN_MATRICULA = FDF_FUN_MATRICULA
WHERE
    VEN_ID IS NULL;

-- 6°
SELECT DISTINCT
    CLI_NOME AS 'NOME'
FROM
    TB_CLIENTES
        LEFT JOIN
    TB_FONES_CLIENTES ON CLI_ID = FDC_CLI_ID
        JOIN
    TB_PESSOAS_FISICAS ON CLI_ID = CPF_CLI_ID
WHERE
    FDC_FONE IS NULL;

-- 7°
SELECT DISTINCT
    FOR_NOME_FANTASIA AS 'NOME FANTASIA', FDF_FONE AS 'FONE'
FROM
    TB_FORNECEDORES
        JOIN
    TB_COMPRAS ON FOR_ID = COM_FOR_ID
        JOIN
    TB_FONES_FORNECEDORES ON FOR_ID = FDF_FOR_ID;

-- 8°
SELECT DISTINCT
    FOR_NOME_FANTASIA AS 'NOME FANTASIA', FDF_FONE AS 'FONE'
FROM
    TB_FORNECEDORES
        LEFT JOIN
    TB_COMPRAS ON FOR_ID = COM_FOR_ID
        JOIN
    TB_FONES_FORNECEDORES ON FOR_ID = FDF_FOR_ID
WHERE
    COM_ID IS NULL;